name: Creates and Updates PR
on:
  push:
    branches:
    - main
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: update-pull-request
      uses: kt3k/update-pr-description@v1.0.1
      with:
        pr_body: "**some description**"
        github_token: ${{ secrets.GITHUB_TOKEN }}
